1711h
fd1-53-17/Alex030389 pull request #17
Opened 2017-11-19 18:32 UTC by Alex030389

@antonkulakov-it please review

2017-11-19 20:31 UTC, antonkulakov-it requested changes

2017-11-19 20:31 UTC, antonkulakov-it commented on 1711h/2/assets/css/main.css
> +	background-image: url(../img/white/ferz.png);
задача выполнена не верно!
Вам не нужно вырезать отдельные фигуры. Используйте спрайт - один файл со всеми фигурами.

2017-11-20 13:41 UTC, Alex030389 commented
@antonkulakov-it please review

2017-11-20 13:42 UTC, Alex030389 commented
@antonkulakov-it please review

2017-11-22 03:47 UTC, antonkulakov-it approved these changes

2017-11-22 03:47 UTC, merged